-- THIS FILE IS AUTO-GENERATED, WOULD BE OVERWRITTEN BY GUI-EDITOR
local component = require '@common.base.gui.component'
local bind = component.bind
local call = component.call
local gui_pkg = require '@common.base.gui.package'
local get_text = gui_pkg.get_text() or get_text
local on_player_prop = require '@common.base.gui.on_player_prop'
local on_unit_prop = require '@common.base.gui.on_unit_prop'
local ctrl_wrapper = require '@common.base.gui.ctrl_wrapper'


local smallcard_scoreboard = require '@smallcard_scoreboard.component'
local lib_gamechat = require '@lib_gamechat.component'
local smallcard_inventory = require '@smallcard_inventory.component'
local gameui = require '@gameui.component'
local smallcard_unit_attr_panel = require '@smallcard_unit_attr_panel.component'
local lib_game_options = require '@lib_game_options.component'
local lib_control = require '@lib_control.component'
local smallcard_choose_one = require '@smallcard_choose_one.component'

return gui_pkg.page_template {
    flatten_template = {
        ctrl_wrapper.panel {
            __EDIT_TIME = {
                lock = true,
            },
            layout = {
                grow_height = 1,
                grow_width = 1,
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
            },
            name = 'MainPage',
            show = true,
        },0,
        lib_game_options.设置按钮 {
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 100,
                ratio = {},
                relative = {
                    [1] = -100,
                    [2] = 200,
                },
                row_self = 'end',
                width = 100,
            },
            name = '设置按钮1',
            show = false,
        },1,
        gameui.Buff列表 {
            buff_cat_filter = '可被禁用;负面效果',
            buff_height = 64,
            buff_icon = 'image/msgbox/btn_1.png',
            buff_icon_template = '@gameui.prefab.buff.buff_icon',
            buff_margin = 7,
            buff_polarity = '正面;负面;无',
            buff_width = 64,
            default_neg_cnt = 3,
            default_none_cnt = 3,
            default_pos_cnt = 3,
            layout = {
                col_self = 'end',
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -220,
                },
                row_self = 'center',
            },
            name = 'Buff列表',
        },1,
        smallcard_inventory.背包入口 {
            layout = {
                col_self = 'end',
                ratio = {},
                relative = {
                    [1] = 600,
                    [2] = -50,
                },
                row_self = 'center',
            },
            name = '背包入口2',
        },1,
        smallcard_choose_one.N选1_整体面板 {
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = 'N选1_整体面板2',
            show = false,
        },1,
        smallcard_unit_attr_panel.单位属性面板 {
            bind_unit = 0,
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 72,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 714,
            },
            name = '单位属性面板3',
        },1,
        ctrl_wrapper.panel {
            color = 'rgba(255, 255, 255, 0.0000)',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 180,
                position = {},
                ratio = {},
                relative = {
                    [1] = -50,
                    [2] = 50,
                },
                row_self = 'end',
                width = 270,
            },
            name = '计分板',
        },1,
        ctrl_wrapper.panel {
            color = 'rgba(255, 255, 255, 0.3922)',
            layout = {
                col_self = 'center',
                height = 800,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 1000,
            },
            name = '游戏结果',
            show = false,
        },1,
        ctrl_wrapper.label {
            font = {
                size = 100,
            },
            layout = {
                col_self = 'start',
                height = 150,
                position = {},
                ratio = {},
                relative = {
                    [1] = 50,
                    [2] = 50,
                },
                row_self = 'start',
                width = 350,
            },
            name = '显示金钱',
            text = '文本',
        },1,
        ctrl_wrapper.button {
            color = 'rgba(255, 255, 35, 1.0000)',
            event = {
                on_click = call{client = '@ragnarok_xanb.gui.ui_response.点击修建_等级1',},
            },
            layout = {
                col_self = 'start',
                height = 100,
                position = {},
                ratio = {},
                relative = {
                    [1] = 46.28564453125,
                    [2] = 940.62487792969,
                },
                row_self = 'start',
                width = 300,
            },
            name = '抽卡_等级1',
        },1,
        ctrl_wrapper.label {
            font = {
                size = 60,
                stroke = 2,
                stroke_color = 'rgba(255, 0, 0, 1.0000)',
            },
            layout = {
                col_self = 'center',
                height = 120,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -150,
                },
                row_self = 'center',
                width = 350,
            },
            name = '文字提示',
            show = false,
            text = '文本',
        },1,
        ctrl_wrapper.button {
            color = '#232323',
            layout = {
                col_self = 'start',
                height = 40,
                position = {},
                ratio = {},
                relative = {
                    [1] = -1652.4058837891,
                    [2] = 248.67749023438,
                },
                row_self = 'start',
                width = 120,
            },
            name = 'button64',
        },2,
        ctrl_wrapper.label {
            font = {
                bold = true,
                color = 'rgba(192, 176, 155, 1.0000)',
                family = 'SourceHanSerif',
                size = 50,
            },
            layout = {
                col_self = 'start',
                height = 72,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 90,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'label1b',
            text = '选择技能',
        },5,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_choose_one/image/title_l.png',
            layout = {
                col_self = 'start',
                height = 32.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = -432.0,
                    [2] = 110.0,
                },
                row_self = 'center',
                width = 550.0,
            },
            name = 'panel1a',
        },5,
        ctrl_wrapper.panel {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_choose_one/image/title_r.png',
            layout = {
                col_self = 'start',
                height = 32.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 432,
                    [2] = 110.0,
                },
                row_self = 'center',
                width = 551.0,
            },
            name = 'panel1a',
        },5,
        smallcard_choose_one.N选1_选择面板 {
            layout = {
                col_self = 'center',
                grow_height = 1,
                grow_width = 1,
                position = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
            },
            name = 'N选1_选择面板5',
        },5,
        smallcard_choose_one.N选1_确认按钮 {
            border = {
                bottom = 25.130434782609,
                left = 29.565217391304,
                right = 29.565217391304,
                top = 14.782608695652,
            },
            image = '@smallcard_choose_one/image/button.png',
            layout = {
                col_self = 'end',
                height = 99.0,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -190,
                },
                row_self = 'center',
                width = 408.0,
            },
            name = 'N选1_确认按钮3',
            text = '确定',
        },5,
        smallcard_choose_one.N选1_关闭面板 {
            layout = {
                col_self = 'start',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = -100.0,
                    [2] = 100.0,
                },
                row_self = 'end',
                width = 48,
            },
            name = 'N选1_关闭面板4',
        },5,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '等级',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@ragnarok_xanb/image/icons/星星_star.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 60,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },6,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '攻击',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@ragnarok_xanb/image/icons/攻击.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 222,
                    [2] = 0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },6,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '护甲值',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@ragnarok_xanb/image/icons/防御.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 384,
                    [2] = 0.0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },6,
        smallcard_unit_attr_panel.单位属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            bind_attr = '生命',
            cat_button_height = 132,
            font_color = '#FFFFFF',
            font_family = 'Regular',
            font_size = 30,
            icon = '@ragnarok_xanb/image/icons/生命.png',
            layout = {
                col_self = 'center',
                direction = 'row',
                height = 48,
                position = {},
                ratio = {},
                relative = {
                    [1] = 546,
                    [2] = 0.0,
                },
                row_content = 'start',
                row_self = 'start',
                width = -1,
            },
            name = '单位属性4',
            show_mode = 0,
        },6,
        ctrl_wrapper.panel {
            color = 'rgba(0, 0, 0, 0.3020)',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 270,
            },
            name = '1号玩家',
        },7,
        ctrl_wrapper.panel {
            color = 'rgba(0, 0, 0, 0.3020)',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 48,
                },
                row_self = 'center',
                width = 270,
            },
            name = '2号玩家',
        },7,
        ctrl_wrapper.panel {
            color = 'rgba(0, 0, 0, 0.3020)',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 96,
                },
                row_self = 'center',
                width = 270,
            },
            name = '3号玩家',
        },7,
        ctrl_wrapper.panel {
            color = 'rgba(0, 0, 0, 0.3020)',
            layout = {
                col_self = 'start',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 144,
                },
                row_self = 'center',
                width = 270,
            },
            name = '4号玩家',
        },7,
        ctrl_wrapper.label {
            font = {
                color = 'rgba(255, 0, 0, 1.0000)',
                size = 200,
            },
            layout = {
                col_self = 'center',
                height = 500,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 0.0,
                },
                row_self = 'center',
                width = 1000,
            },
            name = '游戏结果_文本',
            show = true,
            text = '游戏结果',
        },8,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = -866,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },16,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = -433,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },16,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },16,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 433,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },16,
        smallcard_choose_one.N选1_选项 {
            border = {
                bottom = 0,
                left = 0,
                right = 0,
                top = 0,
            },
            image = '@smallcard_choose_one/image/choose_new_D.png',
            layout = {
                col_self = 'center',
                height = 567,
                margin = {
                    left = 37,
                    right = 37,
                },
                position = {},
                ratio = {},
                relative = {
                    [1] = 866,
                    [2] = -42.5,
                },
                row_self = 'center',
                width = 316,
            },
            name = 'N选1_选项6',
        },16,
        ctrl_wrapper.panel {
            color = 'rgba(100, 95, 194, 1.0000)',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 36,
            },
            name = '排名',
        },23,
        smallcard_scoreboard.玩家名称 {
            font = {
                size = 24,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 48,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '玩家名称7',
            player_id = 1,
        },23,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_scoreboard/image/icon.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 24,
                position = {},
                ratio = {},
                relative = {
                    [1] = -72,
                    [2] = 0,
                },
                row_self = 'end',
                width = 24,
            },
            name = '图标',
        },23,
        smallcard_scoreboard.玩家属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            font = {
                align = 'left',
                size = 24,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'end',
                width = 60,
            },
            name = '玩家属性9',
            player_attr = '补刀',
            player_id = 1,
            show_mode = 0,
        },23,
        ctrl_wrapper.panel {
            color = 'rgba(67, 92, 154, 1.0000)',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 36,
            },
            name = '排名',
        },24,
        smallcard_scoreboard.玩家名称 {
            font = {
                size = 24,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 48,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '玩家名称7',
            player_id = 2,
        },24,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_scoreboard/image/icon.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 24,
                position = {},
                ratio = {},
                relative = {
                    [1] = -72,
                    [2] = 0,
                },
                row_self = 'end',
                width = 24,
            },
            name = '图标',
        },24,
        smallcard_scoreboard.玩家属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            font = {
                align = 'left',
                size = 24,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'end',
                width = 60,
            },
            name = '玩家属性9',
            player_attr = '补刀',
            player_id = 2,
            show_mode = 0,
        },24,
        ctrl_wrapper.panel {
            color = 'rgba(102, 155, 91, 1.0000)',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 36,
            },
            name = '排名',
        },25,
        smallcard_scoreboard.玩家名称 {
            font = {
                size = 24,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 48,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '玩家名称7',
            player_id = 3,
        },25,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_scoreboard/image/icon.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 24,
                position = {},
                ratio = {},
                relative = {
                    [1] = -72,
                    [2] = 0,
                },
                row_self = 'end',
                width = 24,
            },
            name = '图标',
        },25,
        smallcard_scoreboard.玩家属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            font = {
                align = 'left',
                size = 24,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'end',
                width = 60,
            },
            name = '玩家属性9',
            player_attr = '补刀',
            player_id = 3,
            show_mode = 0,
        },25,
        ctrl_wrapper.panel {
            color = 'rgba(132, 79, 55, 1.0000)',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'start',
                width = 36,
            },
            name = '排名',
        },26,
        smallcard_scoreboard.玩家名称 {
            font = {
                size = 24,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 48,
                    [2] = 0,
                },
                row_self = 'start',
                width = -1,
            },
            name = '玩家名称7',
            player_id = 4,
        },26,
        ctrl_wrapper.panel {
            color = 'rgba(255,255,255,255)',
            image = '@smallcard_scoreboard/image/icon.png',
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 24,
                position = {},
                ratio = {},
                relative = {
                    [1] = -72,
                    [2] = 0,
                },
                row_self = 'end',
                width = 24,
            },
            name = '图标',
        },26,
        smallcard_scoreboard.玩家属性 {
            accuracy_display = 1,
            attr_multiply = 1,
            font = {
                align = 'left',
                size = 24,
                vertical_align = 'center',
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'end',
                width = 60,
            },
            name = '玩家属性9',
            player_attr = '补刀',
            player_id = 4,
            show_mode = 0,
        },26,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },28,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
            show = true,
        },28,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },28,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },29,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },29,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },29,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },30,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },30,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },30,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },31,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },31,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },31,
        smallcard_choose_one.N选1_选项名称 {
            font = {
                bold = true,
                family = 'SourceHanSerif',
                size = 32,
            },
            layout = {
                col_self = 'start',
                height = 39,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 283,
                },
                row_self = 'center',
                width = -1,
            },
            name = 'N选1_选项名称7',
        },32,
        smallcard_choose_one.N选1_选项图标 {
            layout = {
                col_self = 'start',
                height = 130,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 115,
                },
                row_self = 'center',
                width = 130,
            },
            mask_image = '@smallcard_choose_one/image/icon_mask.png',
            name = 'N选1_选项图标8',
        },32,
        smallcard_choose_one.N选1_选项描述 {
            font = {
                align = 'center',
                overflow = 'ellipsis',
                size = 24,
                vertical_align = 'top',
            },
            layout = {
                col_self = 'start',
                height = 184,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0.0,
                    [2] = 353,
                },
                row_self = 'center',
                width = 260,
            },
            name = 'N选1_选项描述9',
        },32,
        ctrl_wrapper.label {
            font = {
                size = 30,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 36,
            },
            name = '文本',
            text = '1',
        },33,
        ctrl_wrapper.label {
            font = {
                size = 30,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 36,
            },
            name = '文本',
            text = '2',
        },37,
        ctrl_wrapper.label {
            font = {
                size = 30,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 36,
            },
            name = '文本',
            text = '3',
        },41,
        ctrl_wrapper.label {
            font = {
                size = 30,
            },
            layout = {
                col_self = 'center',
                grow_height = 0,
                grow_width = 0,
                height = 36,
                position = {},
                ratio = {},
                relative = {
                    [1] = 0,
                    [2] = 0,
                },
                row_self = 'center',
                width = 36,
            },
            name = '文本',
            text = '4',
        },45,
    }
}